# Rocket.Chat with a Docker Compose

# Vladimir Mikhalev
# callvaldemar@gmail.com
# www.heyvaldemar.com

# Deploy Rocket.Chat server with a Docker Compose using the command:
# docker-compose -f rocketchat-traefik-letsencrypt-docker-compose.yml -p rocketchat up -d

version: '3.7'

services:
  mongo:
    image: mongo:4.0
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    volumes:
     - rocketchat-mongo:/data/db
     - rocketchat-mongo-dump:/dump
    restart: unless-stopped

  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  rocketchat:
    # Image tag (replace with yours)
    image: rocket.chat:3.8
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    volumes:
      - rocketchat-uploads:/app/uploads
    environment:
      PORT: 3000
      # Rocket.Chat URL (replace with yours)
      ROOT_URL: https://rocketchat.heyvaldemar.net
      MONGO_URL: mongodb://mongo:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      Accounts_UseDNSDomainCheck: 'false'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Rocket.Chat URL (replace with yours)
      - "traefik.http.routers.rocketchat.rule=Host(`rocketchat.heyvaldemar.net`)"
      - "traefik.http.routers.rocketchat.service=rocketchat"
      - "traefik.http.routers.rocketchat.tls.certresolver=letsencrypt"
      - "traefik.http.routers.rocketchat.entrypoints=websecure"
      - "traefik.http.services.rocketchat.loadbalancer.passhostheader=true"
      - "traefik.http.services.rocketchat.loadbalancer.server.port=3000"
    depends_on:
      - mongo

  traefik:
    # Image tag (replace with yours)
    image: traefik:2.3
    command:
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--api=true"
      - "--log.level=WARN"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # Email for Let's Encrypt (replace with yours)
      - "--certificatesresolvers.letsencrypt.acme.email=callvaldemar@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      # Traefik URL (replace with yours)
      - "traefik.http.routers.default.rule=Host(`traefik.heyvaldemar.net`)"
      - "traefik.http.routers.default.service=api@internal"
      - "traefik.http.routers.default.tls.certresolver=letsencrypt"
      - "traefik.http.routers.default.entrypoints=websecure"
      - "traefik.http.services.default.loadbalancer.passhostheader=true"
      - "traefik.http.services.default.loadbalancer.server.port=8080"
      - "traefik.http.routers.default.middlewares=authtraefik"
      # Basic Authentication for Traefik Dashboard
      # Username: traefikadmin (replace with yours)
      # Passwords must be encoded using MD5, SHA1, or BCrypt
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

volumes:
  rocketchat-uploads:
  rocketchat-mongo:
  rocketchat-mongo-dump:
  traefik-certificates:
